# Generated by Django 5.1.2 on 2024-10-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_car_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
