# Generated by Django 5.1.2 on 2025-02-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
