# Generated by Django 5.1.2 on 2025-02-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_cars_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media\\cars\\cars_photo'),
        ),
    ]
